### ISSUE TITLE
Getting Error Converting INR TO AED

### ISSUE THREAD

**Issue by rd67** [fixerAPI/fixer#103]
Getting Response - 
```
{
error: "Invalid base"
}
```

when trying - https://api.fixer.io/latest?symbols=INR&base=AED

And when tried - the reverse - https://api.fixer.io/latest?symbols=AED&base=INR
Got following response - 
```
{
base: "INR",
date: "2018-02-13",
rates: { }
}
```

**Comment by fbartolini** [comment]
I think this is happening because AED is not a published exchange rate by the ECB.

**Comment by rd67** [comment]
@fbartolini Thanks for your reply.
Can you suggest any way by which I can get the converted rates of all countries. My website will be dealing with multiple Currencies.

**Comment by fbartolini** [comment]
@rohitdalal67 ,

I was pulling this from a server that runs PHP and then updating a service I have somewhere else, all I did was pull the rates that were available in ECB from fixer, and the rest from currencylayer.com, which offers a free service for up to 1000 calls/month. Here is my function in PHP. 

`
function fetchRates($base,$currencies,$missing=null){
	if($missing)
		$url = 'http://apilayer.net/api/live?access_key=YOUR_CURRENCYLAYER_API_KEY&currencies='.implode(",",$currencies)."&source=".$base."&format=1";
	else
		$url = "https://api.fixer.io/latest?symbols=".implode(",",$currencies)."&base=".$base;
	$s = curl_init(); 
	curl_setopt($s,CURLOPT_URL,$url);
	curl_setopt($s, CURLOPT_HEADER, 0);  
	curl_setopt($s, CURLOPT_RETURNTRANSFER, true); 
	$result = json_decode(curl_exec($s));
	curl_close($s);
	return $result;
}
`

**Comment by rd67** [comment]
@fbartolini Thanks for your help
