### ISSUE TITLE
magento 2 We can't retrieve a rate from http://api.fixer.io/latest?base=E

### ISSUE THREAD

**Issue by googelie** [fixerAPI/fixer#104]
We can't retrieve a rate from http://api.fixer.io/latest?base=EUR&symbols=AED,AFN,ALL,AMD,ANG,AOA,ARS,AUD,AWG,AZM,AZN,BAM,BBD,BDT,BGN,BHD,BIF,BMD,BND,BOB,BRL,BSD,BTN,BUK,BWP,BYR,BZD,CAD,CDF,CHE,CHF,CHW,CLP,CNY,COP,CRC,CUP,CVE,CZK,DJF,DKK,DOP,DZD,EEK,EGP,ERN,ETB,EUR,FJD,FKP,GBP,GEK,GEL,GHS,GIP,GMD,GNF,GQE,GTQ,GYD,HKD,HNL,HRK,HTG,HUF,IDR,ILS,INR,IQD,IRR,ISK,JMD,JOD,JPY,KES,KGS,KHR,KMF,KPW,KRW,KWD,KYD,KZT,LAK,LBP,LKR,LRD,LSL,LTL,LVL,LYD,MAD,MDL,MGA,MKD,MMK,MNT,MOP,MRO,MUR,MVR,MWK,MXN,MYR,MZN,NAD,NGN,NIC,NOK,NPR,NZD,OMR,PAB,PEN,PGK,PHP,PKR,PLN,PYG,QAR,RHD,ROL,RON,RSD,RUB,RWF,SAR,SBD,SCR,SDG,SEK,SGD,SHP,SKK,SLL,SOS,SRD,STD,SVC,SYP,SZL,THB,TJS,TMM,TND,TOP,TRL,TRY,TTD,TWD,TZS,UAH,UGX,USD,UYU,UZS,VEB,VEF,VND,VUV,WST,XCD,XOF,XPF,YER,ZAR,ZMK,ZWD for AED.

**Comment by AnthonyLiu** [comment]
The data comes from https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html

http://fixer.io only support listed rates.
