### ISSUE TITLE
Resaults are 3 days old

### ISSUE THREAD

**Issue by sid606** [fixerAPI/fixer#105]
Hi 

When I try to get response it give me  "date": "2018-03-02", but we are 2018-03-05 how is this possible.
I'm using "https://api.fixer.io/latest?symbols=USD,GBP,EUR,CHF,ZAR,AUD,NZD&base=GBP"

**Comment by AnthonyLiu** [comment]
Browser cookie? Try hard refresh

**Comment by sid606** [comment]
this was returned from postman and from php curl :( today 2018-3-6 it returns  2018-03-05

**Comment by cameronws** [comment]
I would think that it's because the updates only happen after a specific time once a day.

> The API updates rates daily around 4PM CET every working day
