### ISSUE TITLE
Capabilities endpoint

### ISSUE THREAD

**Issue by diadistis** [fixerAPI/fixer#108]
I'm thinking to create a fixer extension for our ERP and it would be great if there was an endpoint that describes the capabilities available for a given API key in order to automatically enable/disable features accordingly. Ideally it should contain the available endpoints, limits and refresh rates in order to automate the scheduling of the update process. For example at the free plan you get 1000 requests per month with hourly refresh rate so while you can do ~33 requests per day there is no need for more than 24 and that is also true for the Basic plan.

**Comment by Schusti91** [comment]
Hi @diadistis,

This is the legacy API of fixer.io, I will update our feature-request list with your requirement.

Best,
Andreas
