### ISSUE TITLE
changing base no longer allowed? what's the point of the free API then?

### ISSUE THREAD

**Issue by aleqx** [fixerAPI/fixer#109]
So with the API change it seems you also restricted the change of base currency, i.e. http://data.fixer.io/api/latest?access_key={key}&base=USD&symbols=AUD

now says

`{"success":false,"error":{"code":105,"type":"base_currency_access_restricted"}}`

I fail to see the point in offering a free API if it's so restricted (only EUR base).

**Comment by downhiller** [comment]
Agreed.  Why make it free to people with EUR as a base, but not with anything else as a base?  Maybe limit each account to one base, but let it be whatever people want.  If you look in their closed issues you'll find a rival (truly free) service someone else has set up which is a straight swap, no need to change any code other than the domain name.

**Comment by aleqx** [comment]
> If you look in their closed issues you'll find a rival (truly free) service someone

I've also switched away from fixer.io when I saw their hidden restrictions (*) to this https://free.currencyconverterapi.com which seems to work well (100 API calls/hour limit, which is generous compared to others). There's also https://forex.1forge.com which is super fast but has fewer pairs (and 1000 API calls/day limit).

(*) that's another aspect: they implemented this restriction <s>but said nothing about it (unless I missed the memo), which isn't cool</s>

**Comment by downhiller** [comment]
It is mentioned on their "pricing" page, but not that clearly.

**Comment by gingerlime** [comment]
Looks like someone created a [fixer.io compatible service](https://exchangeratesapi.io/) see https://github.com/fixerAPI/fixer/issues/107#issue-313114059

(not affiliated in any way, just discovered this when our API calls suddenly failed)

**Comment by aleqx** [comment]
@gingerlime ok, that's actually pretty useful (updating my scripts will take a little less time)

**Comment by guncebektas** [comment]
@gingerlime https://exchangeratesapi.io is really good and very easy to switch

**Comment by chadsaun** [comment]
@guncebektas - All I had to do was replace the domain name! 👍👍🎉

**Comment by aleqx** [comment]
@chadsaun it's great indeed, give the original author of it some kudos here https://github.com/fixerAPI/fixer/issues/107#issue-313114059

**Comment by kevinjsuh** [comment]
FYI - fixer is scraping a public source (the [ECB](https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html)) and charging $10/mo for a layer on top of it.

https://exchangeratesapi.io/ https://github.com/fixerAPI/fixer/issues/107#issue-313114059 uses the same public ECB source. Major props to the author!

**Comment by AnonymousArthur** [comment]
fixer.io is equal to currencylayer.com now, their dashboard is 90%, pricing is 100% the same. I guess they are running by the same team/company and try to make them profitable.

**Comment by Schusti91** [comment]
Hi,

Andreas from fixer.io here.

@aleqx 

Exactly for this reason we created the legacy subscription, which offers the Free plan + SSL & changing base currency.

> **Legacy Plan**
> For a limited period of time we are also offering a Free Legacy Plan for all legacy users. This plan comes with free SSL support and the ability to change base currency. [You can sign up for the Legacy Plan here.](https://fixer.io/signup/legacy)

(from https://github.com/fixerAPI/fixer/blob/master/README.md)

Best,

**Comment by erf** [comment]
@Schusti91 will the legacy subscription work indefinitely as long as we are signed up now?

**Comment by Schusti91** [comment]
@erf The availability of the legacy plan is limited because it's only supposed to ensure an easy migration to the new Fixer service for all existing customers. However, once you are subscribed, it won't change unless you upgrade/downgrade to a different plan on your own.

**Comment by JerryBels** [comment]
Wanting to make your service profitable is absolutely fine, but I think you made a really bad call by preventing people from choosing their base currency.

I can speak only for myself but I see here more people that took the exact same path as I did : tried to migrate to stick with fixer.io, getting the error about restricted base currency, looking for an alternative. At first I thought, okay, I don't need much for now and if someday I do I will simply subscribe for a paid plan. Now you simply lost me - and others.

**Comment by Schusti91** [comment]
@JerryBels To prevent this bad experience (with the restricted base currency) we created the legacy plan for all GitHub users.

> Legacy Plan
> For a limited period of time we are also offering a Free Legacy Plan for all legacy users. This plan comes with free SSL support and the ability to change base currency. [You can sign up for the Legacy Plan here.](https://fixer.io/signup/legacy)

(from https://github.com/fixerAPI/fixer/blob/master/README.md)

**Comment by JerryBels** [comment]
@Schusti91 sure, it is... But it's not that obvious for whoever doesn't want to look that hard for a solution with fixer. I really hope for you guys that you'll get what you're looking for. All the best.

**Comment by thekrotek** [comment]
Completely agree, that with base currency limitation Fixed became useless to most people. There're plenty alternative API with the same functionality, but without base currency restriction. I understand all the monetization concept, but you should really be careful with it and don't overmonetize.

**Comment by danoli3** [comment]
Absolutely the BEST management decision I have ever seen for an API... 

Lets kill the basic API with no proper API Depreciation or legal warning time... and to make it better let's kill the BASE currency setter ... cause that will totally make you money...

Oh wow look free alternatives with the same API style. RIP Fixer.
https://exchangeratesapi.io/

**Comment by cjshaw1976** [comment]
Goodbye fixer.io, hello exchangeratesapi.io

**Comment by Schusti91** [comment]
@thekrotek @danoli3 @cjshaw1976 to ease your migration from the old the new API (restricted base currency) we created the legacy plan for all GitHub users.

> Legacy Plan
> For a limited period of time we are also offering a Free Legacy Plan for all legacy users. This plan comes with free SSL support and the ability to change base currency. Once you are subscribed, it won't change unless you upgrade/downgrade to a different plan on your own.
> 
> [You can sign up for the Legacy Plan here.](https://fixer.io/signup/legacy)

(from https://github.com/fixerAPI/fixer/blob/master/README.md)

**Comment by commonpike** [comment]
related issue with a few solutions 
https://github.com/fixerAPI/fixer/issues/107

**Comment by Albertjvanr** [comment]
If you are using some automation software, like Home Assistant... Just create two sensors for the currencies you want to compare, both relative to EURO, and then divide them by each other to get them relative to each other... :-)

**Comment by mitmelon** [comment]
Lol!! there is a simple hack to get what you want... follow this guide below..

Lets assume your base currency is USD and you want to convert 25 USD to NGN or any other currency. All you have to do is to 

Convert 25EUR to USD and NGN

Which should give you the result like this 

```
Array
(
    [date] => 2021-02-02
    [converted] => Array
        (
            [0] => Array
                (
                    [NGN] => 11515.55225
                )

            [1] => Array
                (
                    [USD] => 30.204725
                )

            [2] => Array
                (
                    [GBP] => 22.044925
                )

        )
)
```

You can see you have USD as 30.204725

Subtract 30.204725USD - 25EUR = 5.204725

Now subtract 25EUR - 5.204725 = 19.795275

Now convert 19.795275EUR to USD you get 

```
Array
(
    [date] => 2021-02-02
    [converted] => Array
        (
            [0] => Array
                (
                    [NGN] => 9118.1409426248
                )

            [1] => Array
                (
                    [USD] => 23.916433506975
                )

            [2] => Array
                (
                    [GBP] => 17.455414109175
                )

        )
)
```
Looking at the result above, its means 23.916433506975USD equates 9118.1409426248NGN (Target Currency)

But you are looking for 25USD. So now 

25 - 23.916433506975USD to get the difference remaining to complete the 25USD

Ans = 1.083566493025

Now add 1.083566493025 to 19.795275 you have 20.878841493025

Now convert 20.878841493025EUR to USD

```
Array
(
    [date] => 2021-02-02
    [converted] => Array
        (
            [0] => Array
                (
                    [NGN] => 9617.2556052959
                )

            [1] => Array
                (
                    [USD] => 25.225586624616
                )

            [2] => Array
                (
                    [GBP] => 18.410899792025
                )

        )
)
```
You have 25.225586624616USD... Which is still okay... at least you are sure no loss will be observed

So finally you have 20.878841493025EUR to get 25.225586624616USD

If lucky, you can write a program that does all the job... but i will advise you just pay for the premium service

**Comment by thoughtspile** [comment]
Now it's 2021 and guess what exchangeratesapi did? 
`'error': { 'code': 105, 'type': 'base_currency_access_restricted' } }`
The website layout looks the same as fixer's. See some strategic thinking in there.

**Comment by gingerlime** [comment]
I forgot to post this, but a rather long while back we switched from fixer.io to https://www.frankfurter.app/ which is built by the original creator of fixer.io ... again no affiliation, and apart from literally [one minor blip](https://github.com/hakanensari/frankfurter/issues/13) it's been very stable and reliable so far.

**Comment by lochiwei** [comment]
> @gingerlime https://exchangeratesapi.io is really good and very easy to switch

same thing with `http://api.exchangeratesapi.io/latest?access_key=API_KEY&base=CAD` (free plan):

response:
```
{"success":false,"error":{"code":105,"type":"base_currency_access_restricted"}}
```

**base_currency_access_restricted** ❗

**Comment by APTEMOH** [comment]
**=>** https://github.com/APTEMOH/currency_parser_free
