### ISSUE TITLE
Can you please re-enable your old API for couple more days.

### ISSUE THREAD

**Issue by narekgevorgyan** [fixerAPI/fixer#110]
I'm writing on behalf of a big app which been using your old API. We were late updating our app and just noticed users are getting an error message when using our app.

Happy to help you with anything you'd like to, but really need your favour today!

**Comment by Schusti91** [comment]
Hi @narekgevorgyan,

We notified on various channels since March about the scheduled shutdown
- Github announcement
- Website
- Deprecation message in JSON response of api.fixer.io

We are aware that this is a tough decision, but we are not able to enable the legacy API again.
