### ISSUE TITLE
I got my new API key, however google rejects your http backend since I have an SSL installed

### ISSUE THREAD

**Issue by inglesuniversal** [fixerAPI/fixer#112]
Any workarounds on how to force to load your API through https:// ?

Thanks

**Comment by Schusti91** [comment]
@inglesuniversal  to ease your migration from the old the new API (restricted base currency) we created the legacy plan for all GitHub users.

> Legacy Plan
> For a limited period of time we are also offering a Free Legacy Plan for all legacy users. This plan comes with free SSL support and the ability to change base currency. Once you are subscribed, it won't change unless you upgrade/downgrade to a different plan on your own.
> 
> [You can sign up for the Legacy Plan here.](https://fixer.io/signup/legacy)

(from https://github.com/fixerAPI/fixer/blob/master/README.md)
