### ISSUE TITLE
FX rates no longer getting updated?

### ISSUE THREAD

**Issue by tarioch** [fixerAPI/fixer#14]
http://api.fixer.io/latest currently returns a date of 2015-12-22 but looking at http://www.ecb.europa.eu/stats/exchange/eurofxref/html/index.en.html there should be newer exchange rates.

**Comment by tarioch** [comment]
Also http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml seems to be up to date.

**Comment by hakanensari** [comment]
@tarioch thanks for the heads-up :+1:
