### ISSUE TITLE
Server Error 500 on many requests

### ISSUE THREAD

**Issue by levino** [fixerAPI/fixer#17]
Happens when I query in parallel or sequentially.

**Comment by levino** [comment]
Today no more issues. Maybe something fixed itself.

**Comment by hakanensari** [comment]
I did find a problem setting in the nginx sitting in front of the app server. Good to hear the issue went away.

This actually had been [reported before](https://github.com/hakanensari/fixer-io/issues/15), but I had brushed it aside.

**Comment by ajimix** [comment]
Today I'm getting also error 500 in some requests. So far I've been using the API for a while and it always worked well, but today I started getting the error :(

Thanks for your time

**Comment by hakanensari** [comment]
@ajimix I increased server capacity after a spike in activity. Everything should be back to normal now.

**Comment by levino** [comment]
@hakanensari Who is paying for this?
