### ISSUE TITLE
Missing currencies

### ISSUE THREAD

**Issue by jjvvx** [fixerAPI/fixer#20]
The following currencies are missing:

Hong Kong Dollar
Taiwan Dollar
Maccanese Pataca
Mexican peso
All South American currencies
Most East Asian currencies
All Middle Eastern currencies
Bitcoin
Russian Ruble

I personally needed the ARS, UYU and HKD, but the above list is of the ones that I found.

**Comment by hakanensari** [comment]
We're just mirroring the [rates from the European Central Bank](https://www.ecb.europa.eu/stats/exchange/eurofxref/html/index.en.html). If they don't provide a rate, Fixer won't have it.
