### ISSUE TITLE
Hi, is this a problem with IDR?

### ISSUE THREAD

**Issue by rtm375** [fixerAPI/fixer#24]
I tried to get latest currency, i put IDR as the base, http://api.fixer.io/latest?base=IDR but i can't understood the number.

Example EUR return value of 6.6552e-05 and USD return 7.5723e-05.

I don't know what this is mean, please help, thanks!

**Comment by hakanensari** [comment]
I'm not sure if there's a way to avoid scientific notation here without casting to string. Is there an issue using these values, or is it just that the notation caught you off guard?

**Comment by rtm375** [comment]
Thanks for your reply. But it's okay. I already changed my function from IDR - EUR to EUR - IDR, and it works well for me.
On Jun 9 2016, at 8:32 pm, Hakan Ensari notifications@github.com wrote:

I'm not sure if there's a way to avoid scientific notation here without casting to string. Is there an issue using these values, or is it just that the notation caught you off guard?
