### ISSUE TITLE
Conversion API?

### ISSUE THREAD

**Issue by mwarkentin** [fixerAPI/fixer#25]
First off, great project! Nice to see a fully open-source exchange rate API.

Any thoughts on exposing an API that does the actual conversion between one currency and another?

It would take in three required params:
- `amount`
- `from`
- `to`

Optionally, it could take a `date` parameter which would convert at a historical rate.

Thanks!

**Comment by kingIZZZY** [comment]
Yeah, come on, show us the REAL conversion API please! :wink:

**Comment by albinekb** [comment]
@hakanensari this one can be closed 😄
