### ISSUE TITLE
Mistake with convert USD to AED

### ISSUE THREAD

**Issue by roger34000** [fixerAPI/fixer#26]
Hi everybody,

I tried to convert USD to AED and AED to USD :
- http://api.fixer.io/latest?symbols=USD&base=AED
- http://api.fixer.io/latest?symbols=AED&base=USD

The twice returns is : {"error":"Invalid base"}.

Can you help me ?

**Comment by hakanensari** [comment]
The European Central Bank doesn't provide data for AED. Try [Open Exchange Rates](https://openexchangerates.org).

**Comment by roger34000** [comment]
thx
