### ISSUE TITLE
Please add TWD!

### ISSUE THREAD

**Issue by LawreyTan** [fixerAPI/fixer#29]
Please add TWD!

**Comment by acidjazz** [comment]
In  need of this as well!!

**Comment by ArchitW** [comment]
Same

**Comment by Jbithell** [comment]
Hi @LawreyTan, @acidjazz & @ArchitW - as I understand it, this library uses the data provided by the European Central Bank (ECB). The ECB produces a list of currencies they currently support: https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html and TWD isn't currently on the list so I don't think it would be that simple to add this currency to the library, but it's maintainers may have ideas!
