### ISSUE TITLE
List libraries using Fixer.io

### ISSUE THREAD

**Issue by florianv** [fixerAPI/fixer#32]
It would be nice to list libraries using Fixer.io in various languages.

For example, these two projects allow to retrieve latest and historical rates from Fixer.io in PHP
- https://github.com/florianv/exchanger 
- https://github.com/florianv/swap

**Comment by hakanensari** [comment]
Perhaps we could create a Wiki entry for libraries and websites that use the API and reference the URL in the README?

**Comment by florianv** [comment]
Yes it would be great :)
