### ISSUE TITLE
Please add ARS - Argentine Peso

### ISSUE THREAD

**Issue by netpastor** [fixerAPI/fixer#36]

**Comment by netpastor** [comment]
And PEN - Peruvian Nuevo

**Comment by tohyongcheng** [comment]
need this too 👍

**Comment by CanRau** [comment]
+1 for PEN

**Comment by ytho** [comment]
fixer.io gets it exchange rates from the [ECB](https://www.ecb.europa.eu). You will have to contact them to add the currency you desire, or you can just use another api that provides the currency you want.

**Comment by CanRau** [comment]
@ytho yeah just realized it :-)
