### ISSUE TITLE
Certificate chain incomplete (actual site)

### ISSUE THREAD

**Issue by nanaya** [fixerAPI/fixer#4]
Unrelated to the app itself but the api site at https://api.fixer.io is missing intermediate certificates, causing error when the said certificate(s) has not been cached by browser (`NET::ERR_CERT_AUTHORITY_INVALID` under Chrome).

Details: https://www.ssllabs.com/ssltest/analyze.html?d=api.fixer.io

Thanks for the app and service, by the way.

**Comment by hakanensari** [comment]
@nanaya1 thanks for the heads-up. I just fixed the certificate and am getting a whopping A :tada:
