### ISSUE TITLE
Switching to the ECB's other API

### ISSUE THREAD

**Issue by brendonboshell** [fixerAPI/fixer#44]
I notice a number of issues open here requesting extra exchange rates. I know the ECB feed currently being used contains a limited number of currencies - for example, it doesn't contain the Taiwan New Dollar.

However, it appears the data from the ECB is also available via their [SDMX REST API](https://sdw-wsrest.ecb.europa.eu/). For example, you can get the USD to EUR exchange rate at the following URL:

```
https://sdw-wsrest.ecb.europa.eu/service/data/EXR/D.USD.EUR.SP00.A?startPeriod=2016-12-15&endPeriod=2016-12-16
```

The benefit of this API is much more currencies are available. For example, replace USD with TWD. Not every currency is available, but far more are available than through the current API.

Would you be willing to accept a pull request to change the API?

**Comment by hakanensari** [comment]
👍 This sounds very interesting, especially if it's a drop-in replacement.

**Comment by GuiSim** [comment]
The URL is actually defined in `fixer`.
https://github.com/hakanensari/fixer/blob/master/lib/fixer/feed.rb#L42

It expects a response with the following format:
http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml

So as far as I know, that would not be a drop-in replacement.

**Comment by GuiSim** [comment]
This is the closest that I found to a daily summary:

https://sdw-wsrest.ecb.europa.eu/service/data/EXR/D..EUR.SP00.A?lastNObservations=1

**Comment by brendonboshell** [comment]
It would not be a drop-in replacement. I did play around with this API from the ECB but I found it to be unreliable. They seem to take it down regularly at weekends (presumably for maintenance), so that would be something else to consider.
