### ISSUE TITLE
XMLHttpRequest cannot load https://api.fixer.io/latest?base=USD. Invalid response. Origin 'null' is therefore not allowed access.

### ISSUE THREAD

**Issue by jnr101** [fixerAPI/fixer#46]
Hi, 

I have built a webpage using angular that makes use of fixer.io data. Now it suddenly stopped working yesterday with the following error. I notice that you made some changes yesterday in the code. Is it anything you can explain, or something broke? When I download the link directly , I get a valid response (in IE, Firefox and Chrome). When I use it in some angular code, it still works in IE, but no longer in Firefox and Chrome. The below is from a session in Chrome:

`XMLHttpRequest cannot load https://api.fixer.io/latest?base=USD. Invalid response. Origin 'null' is therefore not allowed access.`

I am using the following angular code:

```
let fixerURL = "https://api.fixer.io/latest?base=USD";
$http.get(fixerURL).then(
  response => {
    $scope.fixerData = response.data;
  }, error => {
    console.log("Error retrieving data from \"" + fixerURL + "\"!\n" + JSON.stringify(error,null,2));
  }
)
```

The returned error object is:
```
{
  "data": null,
  "status": -1,
  "config": {
    "method": "GET",
    "transformRequest": [
      null
    ],
    "transformResponse": [
      null
    ],
    "url": "https://api.fixer.io/latest?base=USD",
    "headers": {
      "Accept": "application/json, text/plain, */*"
    }
  },
  "statusText": ""
}
```

Thanks
Jarl

**Comment by hakanensari** [comment]
I just reverted a change I suspect was causing this. Thanks for reporting.

**Comment by jnr101** [comment]
Seems to working again. Thanks for looking in to it :-)
