### ISSUE TITLE
Saudi Arab Rial (SAR) support

### ISSUE THREAD

**Issue by biranchi2018** [fixerAPI/fixer#48]
Does it support Saudi Arabia Riyal (SAR) currency ?

**Comment by ytho** [comment]
fixer.io gets its exchange rates from the [ECB](https://www.ecb.europa.eu/).
You can see the ECBs supported currencies [here](https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html)
