### ISSUE TITLE
AFN Unprocessable Entity

### ISSUE THREAD

**Issue by jonwhittlestone** [fixerAPI/fixer#5]
Why is Afghani Unprocessable? Thanks

http://api.fixer.io/latest?base=AFN&symbols=USD

**Comment by hakanensari** [comment]
It's not in the [list of rates](http://www.ecb.europa.eu/stats/exchange/eurofxref/html/index.en.html) published by the ECB, which fixer.io is based on.

You may want to try [OpenExchangeRates](https://openexchangerates.org). They should have AFN.
