### ISSUE TITLE
HTTPS Invalid Certificate

### ISSUE THREAD

**Issue by delances** [fixerAPI/fixer#52]
There is an invalid TLS certificate error when calling fixer.io over HTTPS.

fixer.io uses an invalid security certificate. The certificate is only valid for the following names: *.github.com, github.com, *.github.io Error code: SSL_ERROR_BAD_CERT_DOMAIN

This issue didn't happen yesterday, so I am unsure if the site has been hacked or if a code push yesterday broke something.

**Comment by Fjandin** [comment]
The certificate has expired :(

**Comment by gingerlime** [comment]
Seeing these errors as well. If there's a way to help out, we'd be happy to :)

![screenshot - 190217 - 17 46 49](https://cloud.githubusercontent.com/assets/524274/23104310/833adecc-f6cb-11e6-849e-8b9faf7a3410.png)

**Comment by p-j** [comment]
If it's not the case already, maybe use [Cerbot](https://certbot.eff.org/) for automatic renewal of Let's Encrypt's certificates ?

**Comment by hakanensari** [comment]
I'll fix this tonight. Let's Encrypt seems to be a bit of a moving target.

**Comment by hakanensari** [comment]
Apparently Certbot, scheduled in a cron job, had been silently failing thanks to the `--quiet` switch :anger: I'm hoping to have fixed this by explicitly [specifying the `PATH` in the `crontab` file](https://community.letsencrypt.org/t/letsencrypt-renew-not-working-with-cronjob-manually-it-works/16738).

**Comment by gingerlime** [comment]
Thanks for fixing it so quickly, @hakanensari (and for hosting fixer.io, it's great).

**Comment by delances** [comment]
Thanks for fixing this problem @hakanensari!

**Comment by masciugo** [comment]
thanks!

**Comment by tainmar** [comment]
Thank you @hakanensari ! Fixer.io rocks

**Comment by mattwelke** [comment]
Now that's one free web service people can rely on. Very impressed by the quick fix. :)
