### ISSUE TITLE
Add the last updated time to the response?

### ISSUE THREAD

**Issue by Sweeper777** [fixerAPI/fixer#54]
I know the data updates every day at around 4PM CET. But I want to know when exactly is the data last updated. So can you make it so that there is a `time` in the JSON that tells when is the data last updated if the request has `latest?`?

**Comment by danimahardhika** [comment]
[fixer.io](http://fixer.io/): "Fetch the data sets on ECB", the main source for exchange rates comes from European Central Bank. As you can see [here](http://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html), there's no specific time when actually the rates updated, so this is not possible. This is the original API from ECB http://www.ecb.europa.eu/stats/eurofxref/eurofxref-daily.xml.

Also I think there's a misunderstanding, "exchange rates updated around 4PM CET every working day".

**Comment by Sweeper777** [comment]
Okay, I guess I'll close this then.
