### ISSUE TITLE
Constant 502 errors?

### ISSUE THREAD

**Issue by jbardnz** [fixerAPI/fixer#55]
Around 20% of calls to the API today seem to be returning a 502 error. I understand their is no guarantee of uptime with this API but thought I should make a ticket in case you were unaware.

**Comment by hakanensari** [comment]
It seems the server had run out of TCP ports due to heavier usage in the past few days. [I worked around it for now.](https://ma.ttias.be/linux-increase-ip_local_port_range-tcp-port-range/)

To future-proof this, I suppose I'll have to migrate the setup to scale horizontally and/or rate limit bad clients who request repeatedly the same data instead of caching.

**Comment by erikgeurts** [comment]
@hakanensari Have you looked at the new DigitalOcean load balancers? If you want me to put you in touch with one of the DO account managers, just let me know.

**Comment by mattwelke** [comment]
The rate limiting makes sense. This is a free service and the type of data it provides is a perfect candidate for caching. I think the onus should be on the consumers to cache (or learn how to if they don't know right now) rather than be on you to invest your personal resources in scaling.

**Comment by danieldram** [comment]
I agree. A free service should have an API request limit. One service we use in order to integrate an API at the place I work, limits users to 5 requests per 300 ms (Or 1 request per 60ms). A lot of novice or just typical users often don't throttle their requests to the API otherwise.

**Comment by hakanensari** [comment]
Requests heated up again 🌡 in the past few days, so I have rate-limited the API to 5 requests per second per IP.

**Comment by jackfruhecolab** [comment]
Great Service! 
Please consider posting the rate limit value to the home fixer.io home page.

I created a powershell script to pull rates and cache them, but initially it just went full force.
seeing the comment above allowed me to insert a sleep 500ms cycle between requests to spread the load out over time.

Also, my use case is to pull a specific conversion (IRN to USD) but for every day for the past few years (Hence the large number of requests, one per day)

I don't know if it's practical, but if there was a way to pull a date _range_ in one request, I could replace a bunch of requests for a single date with a single request for the time period I'm interested in.

Either way, great work on this api! Let me know if there is a place to donate.

**Comment by hakanensari** [comment]
@jackfruhecolab, yes, I will explain rate limiting on the homepage and will be adding a range endpoint eventually. You can follow [this issue](https://github.com/hakanensari/fixer-io/issues/22) to keep up-to-date.

There's no place to donate, but thanks!
