### ISSUE TITLE
Multiple parameters fail on path :latest 

### ISSUE THREAD

**Issue by jasonm23** [fixerAPI/fixer#58]
For example:

```
curl http://api.fixer.io/latest?base=SGD&symbols=AUD
```

Expect to see AUD only with base rate of SGD. Instead base is set to SGD but many symbols are returned.

Flipping the parameters like so:

```
curl http://api.fixer.io/latest?symbols=AUD&base=SGD
```

Reveals that only one param is actioned, base rate is reported as EUR and only AUD symbol is returned.

**Comment by hakanensari** [comment]
The terminal is messing with your ampersand. Try putting the URL in quotes.

**Comment by danieldram** [comment]
I can confirm that, if you take the same URL provided in the example and place it in the URL bar of your browser, it will show what your expect. 

<img width="711" alt="screen shot 2017-03-30 at 9 17 36 pm" src="https://cloud.githubusercontent.com/assets/4514000/24536300/5b74d596-158e-11e7-828a-5235bac58b2f.png">
