### ISSUE TITLE
Wrong date in response

### ISSUE THREAD

**Issue by ozylog** [fixerAPI/fixer#61]
Hi,

i got some issue from API response. exactly when i request this `https://api.fixer.io/2017-04-22?symbols=USD,GBP&base=AUD`

The response will return with date = '2017-04-21' instead of '2017-04-22'. The response is as follows:
`{"base":"AUD","date":"2017-04-21","rates":{"GBP":0.58879,"USD":0.75237}}`

Cheers

**Comment by ozylog** [comment]
i guess it is not a bug. sorry my bad

**Comment by thromera** [comment]
Can we have more explanations? Thanks.
