### ISSUE TITLE
Adding currencies (understanding the challenges)

### ISSUE THREAD

**Issue by rasgo-cc** [fixerAPI/fixer#62]
Hi,

I'm developing [BOMER](http://bomer.co) a software for parts and BOM management (electronics) which uses fixer-io.
I have one request to include Pak Rupee PKR as an available currency.

I noticed there are many currency requests here without any response, so I would like to know what are the challenges/constraints of adding new currencies. Anything I could contribute to fixer-io to get those currencies available?

**Comment by po2go-sean** [comment]
I don't use Fixer.io. I don't work on the code. BUT, I can answer the challenges/constraints question, and why currency requests probably go unanswered:
Fixer.io uses a dataset from the [ECB](http://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html) It can only convert to or from the currencies that are included in the dataset.

Contact ECB asking them to add currency exchange rates.

**Comment by armujahid** [comment]
I emailed ECB today at info@ecb.europa.eu requesting exchange rate of PKR. Lets see what happens

**Comment by rasgo-cc** [comment]
@armujahid any update on that? 
Any of you know other sources like ECB where we can get PKR and other currencies?

**Comment by armujahid** [comment]
@rasgo-xyz ESB hasn't replied yet. 
many other APIs are available. Refer to
https://stackoverflow.com/a/8391430/2073920
