### ISSUE TITLE
Please Support TWD 

### ISSUE THREAD

**Issue by ArchitW** [fixerAPI/fixer#63]
Hello,

Can we support for Taiwan Doller (NT$)
References - 
https://en.wikipedia.org/wiki/New_Taiwan_dollar
http://www.xe.com/currency/twd-taiwan-new-dollar

regards

**Comment by ytho** [comment]
fixer.io gets it exchange rates from the [ECB](https://www.ecb.europa.eu). You will have to contact them to add the currency you desire, or you can just use another api that provides the currency you want.
