### ISSUE TITLE
HTTPS endpoint is not secure.

### ISSUE THREAD

**Issue by puravin** [fixerAPI/fixer#68]
Has the SSL certificate expired?

**Comment by bookt-jacob** [comment]
SSL Cert is expired but the HTTP endpoint appears to be working ok.  Switched over for now.

**Comment by torleifhalseth** [comment]
I can't use  http endpoint because my site is using https.
Are you aware of the issue @hakanensari ? :(

**Comment by hakanensari** [comment]
I omitted defining a renew hook in the certbot cron job to reload nginx. [This blog post](https://www.guyrutenberg.com/2017/01/01/lets-encrypt-reload-nginx-after-renewing-certificates/) talks more about this issue.

This should now be fixed and will hopefully not happen again.

**Comment by bookt-jacob** [comment]
Confirming the fix.  Thank you.
