### ISSUE TITLE
Any chance to get last 90 days Json from an historical date?

### ISSUE THREAD

**Issue by EGcode2000** [fixerAPI/fixer#71]

**Comment by magicmon** [comment]
I agree with you the same way. And, I hope I can set the date range.
like this,

https://api.fixer.io/period?startDate=2010-07-10&endDate=2017-06-03&base=EUR&symbol=USD

**Comment by PhilTheAir** [comment]
+1

**Comment by guicapanema** [comment]
+1

**Comment by kpagcha** [comment]
Time ranges would be a huge feature. +1
