### ISSUE TITLE
Possibility of more traffic

### ISSUE THREAD

**Issue by sem4phor** [fixerAPI/fixer#72]
Hello,
I recently submitted an amazon alexa skill using calls to the API. Is it possible to delimit the calls? I just published a german version so maybe its not even a problem but who knows...

**Comment by hakanensari** [comment]
Do you mean not rate-limit requests from Alexa? I would assume these would come from the devices themselves, in which case there should not be any issue?

**Comment by sem4phor** [comment]
hm im not sure the skill is hosted as a lambda function on AWS. So im not sure maybe you can see it in your logs or metrics? Would be interesting for me to now. Kindly regards
