### ISSUE TITLE
PLN is currently at 0.0

### ISSUE THREAD

**Issue by Calyhre** [fixerAPI/fixer#75]
The [PLN rate is currently 0.0](http://api.fixer.io/latest?symbols=PLN), making the API failed with an error 500 [if the base is set to it](http://api.fixer.io/latest?base=PLN&symbols=PLN).

Maybe a wrong response from the ECB has been cached?

**Comment by Calyhre** [comment]
Seems fixed right now, probably since a re-crawl of the ECB data.

EDIT: I leave this issue open, as for me, it should be more resilient for problems like this. Feel free to close it :)

**Comment by aaokunev** [comment]
Yes, works for me too

**Comment by wolfgangd91** [comment]
http://api.fixer.io/2017-08-28 the API still returns 0 for PLN on this day. would be helpful to edit this rate so people like me working on currency conversion tools can reliably get historical rates

**Comment by hakanensari** [comment]
Very odd. This record on that particular day had bad data, which is also what must have caused the original issue.

I just recreated the database from scratch.
