### ISSUE TITLE
Making a request from a Chrome Extension results in 403?

### ISSUE THREAD

**Issue by yandodov** [fixerAPI/fixer#79]
I made a Chrome Extension that uses fixer.io. When I try it live, I constantly get a 403 response from your server. This also happens if I open the request through my extension from localhost.

I correctly set up my Chrome Extension permissions and even tried making the request to a dummy API:
```
https://jsonplaceholder.typicode.com/posts?base=USD
```
This doesn't return a 403, so the problem is not in my extension manifest. I've added permissions to access all `http` and `https` URLs.

I get a 403 response even if I make that request on fixer.io's very website. The URL I'm requesting is:
```
https://api.fixer.io/latest?base=USD
```
The error I get is:
```
GET https://api.fixer.io/latest?base=USD 403 (Forbidden)
```
The request comes from:
```
chrome-extension://cdddhfgfgancbdapphmamhiadjmgcojp/script.js
```
If I simply make the XHR from the JavaScript console, I get a normal response. I only have problems when my Chrome Extension makes the request, no matter on what website.

Here's the 200 response when I make the request from localhost where I develop my extension:
![fixer200](https://user-images.githubusercontent.com/5570098/31315111-df35f2d0-ac19-11e7-828d-71568be876c5.png)

Here's the 403 response when I make the request from my extension:
![fixer403](https://user-images.githubusercontent.com/5570098/31315112-df37dc1c-ac19-11e7-98e7-cb90c39ca378.png)

Both requests trigger at the same time and the code is the same. One is initialized from a `<script>` on an HTML page, the other is initialized from the extension.

The only differences I could spot between the requests are that the extension request lacks the `Origin` header. Could that be the problem? It also has a `Cookie` header. That one comes from Chrome itself, I doubt it causes the problem, though.

I also wrote about this on [StackOverflow](https://stackoverflow.com/questions/46630329/chrome-extension-xhr-receives-403-response-except-when-initiated-from-file).

Could somebody please help me. Thanks!

**Comment by yandodov** [comment]
The problem can be avoided by initiating the request in an [Event Page](https://developer.chrome.com/apps/event_pages) instead of a [Content Script](https://developer.chrome.com/extensions/content_scripts).

I guess it's because in the context of a Content Script, it's like the currently open website requests some data and CORS problems arise. Event Pages have more permissions, I guess.

**Comment by duplxey** [comment]
> The problem can be avoided by initiating the request in an [Event Page](https://developer.chrome.com/apps/event_pages) instead of a [Content Script](https://developer.chrome.com/extensions/content_scripts).
> 
> I guess it's because in the context of a Content Script, it's like the currently open website requests some data and CORS problems arise. Event Pages have more permissions, I guess.

Did you change anything else? I'm making the calls from `background.js` and I still get `403 Forbidden` error.
