### ISSUE TITLE
Support other Currencies

### ISSUE THREAD

**Issue by enwokoma** [fixerAPI/fixer#81]
For some reasons beyond my understanding, I still don't get why you don't support all other 168 currencies out there?

**Comment by nmolkeri** [comment]
This api publishes the currency rate published by European Central Bank, May be that is the reason they don't have any more currencies.

**Comment by enwokoma** [comment]
Sounds great! But the APIs currently supported currencies is quite a really
small number, I don't know how possible it would be but I really believe it
make much more sense if they can change their source to something like
Yahoo Finance, Google, etc. I don't know, but am just making an honest
suggestion which I believe would propel fixer.io to greater heights!
Just saying!

**Comment by Y0lk** [comment]
Had to stop using the service exactly for that reason. Love the service, love how simple it is, but it needs to support more currencies.

**Comment by enwokoma** [comment]
You are right Gabriel!
Same thing made me stop using their service when I wanted to integrate
currency conversion to my Android App (
https://play.google.com/store/apps/details?id=com.gigabytedevelopersinc.app.calculator),
it's on the app store as CalcMate.
Even my Country's currency isn't supported by fixer.io, so I had to stop
using fixer.io, now decided to use Yahoo Finance and so far so good,
everything works just fine!

They really should do something about it!

**Comment by Sharrisii** [comment]
I would like to see following currencies be added:
xau
xag
btc
ltc
xrp
