### ISSUE TITLE
A Chrome Extension I made with the API.

### ISSUE THREAD

**Issue by yandodov** [fixerAPI/fixer#84]
I just want to share what extension I made with the Fixer API. [Here it is.](https://chrome.google.com/webstore/detail/conveuro/hchlbehbbfdiogoeigibfgjpcmhogaop)

It instantly converts currencies on any page by simply selecting the text.

If you like it, you can maybe put it in a section, called "Made with Fixer" or something and have it on the http://fixer.io/ page. Anyway, thanks for the great API!

**Comment by anshulxyz** [comment]
Hey, great extension. And if you seem to have solved the issue in #79 then please document what the problem was and how you solved it. Then close the issue.

**Comment by yandodov** [comment]
Thanks!

I didn't solve the problem, but I found a workaround that's actually the better way to implement it anyway. I posted it in the issue.
