### ISSUE TITLE
RUB rate is not updated

### ISSUE THREAD

**Issue by sobolevn** [fixerAPI/fixer#86]
For some reason rate of Russian Ruble is not updated for several days. But, that's not true.
Here's the rate changes:
<img width="581" alt="2017-11-21 16 28 39" src="https://user-images.githubusercontent.com/4660275/33074967-0ec3aa92-ced9-11e7-8266-47a51ab7045c.png">
Link: http://www.banki.ru/products/currency/usd/

That's what I get from `fixer`:

```
# https://api.fixer.io/2017-11-17?symbols=USD,EUR&base=RUB
{"base":"RUB","date":"2017-11-17","rates":{"USD":0.016839,"EUR":0.014276}}

# https://api.fixer.io/2017-11-18?symbols=USD,EUR&base=RUB
{"base":"RUB","date":"2017-11-17","rates":{"USD":0.016839,"EUR":0.014276}}

# https://api.fixer.io/2017-11-19?symbols=USD,EUR&base=RUB
{"base":"RUB","date":"2017-11-17","rates":{"USD":0.016839,"EUR":0.014276}}

# https://api.fixer.io/2017-11-20?symbols=USD,EUR&base=RUB
{"base":"RUB","date":"2017-11-20","rates":{"USD":0.016795,"EUR":0.014256}}

# https://api.fixer.io/2017-11-21?symbols=USD,EUR&base=RUB
{"base":"RUB","date":"2017-11-20","rates":{"USD":0.016795,"EUR":0.014256}}
```

Why does it work this way?

**Comment by hakanensari** [comment]
ECB doesn't publish on weekends. The last one is because the daily update takes place at 4 in the afternoon.

**Comment by sobolevn** [comment]
> takes place at 4 in the afternoon

What time zone?

**Comment by hakanensari** [comment]
CET

**Comment by sobolevn** [comment]
Thanks!
