### ISSUE TITLE
new currencies 

### ISSUE THREAD

**Issue by noglance** [fixerAPI/fixer#92]
Hello!

Could you add 'VND','UAH','KZT','GEl','BYR','AZN','AMD' to https://api.fixer.io/latest?base= ?

It would be great!

Thank you.

**Comment by timkrins** [comment]
Fixer used to get its rates from the ECB (European Central Bank).

https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html

These days however, the new API might have the rates you want. You should re-check.
