### ISSUE TITLE
Add cryptocurrencies

### ISSUE THREAD

**Issue by SilencerWeb** [fixerAPI/fixer#93]
Hello!

Don't you want also add cryptocurrencies?

**Comment by Shocker** [comment]
As far as I can see Fixer is meant to provide daily exchange rates. Cryptocurrencies are extremely volatile and would require constant live updating + they are market dependent. It would have to follow hundreds of markets for hundreds of currency pairs => overkill. You have https://cryptowat.ch (or others) for that

**Comment by Sharrisii** [comment]
I think daily exchange rates are sufficient (1x update per day). Also, just the main cryptocurrencies can be followed to reduce the number of cryptocurrencies, if that's needed. Even google finance follows the bitcoin (bitc). Following could be followed:
btc
ltc
eth
xrp

**Comment by SamuelPaltik** [comment]
Or https://coinmarketcap.com/api/

**Comment by ghost** [comment]
There are a lot of API's that are specialised for cryptocurrencies:

- coinapi.io
- cryptocompare.com/api
- coinmarketcap.com/api
