### ISSUE TITLE
I'm try request get method for https://api.fixer.io/2010-10-07?base=CNY&symbols=EUR

### ISSUE THREAD

**Issue by jesoonluo** [fixerAPI/fixer#97]
it return {"error":Not found}
but sometimes it works success for : {"base":"CNY","date":"2010-10-07","rates":{"EUR":0.10718}}
all ways it helps me much more,  thanks for very much!!

when i request: https://api.fixer.io/2010-10-10?base=CNY&symbols=EUR
it return {"base":"CNY","date":"2010-10-08","rates":{"EUR":0.10805}}

**Comment by thromera** [comment]
Same issue here. The date given by the API does not match the request. 

Another example: https://api.fixer.io/2015-04-03
Result: 
```
{"base":"EUR","date":"2015-04-02","rates":{"AUD":1.4343,"BGN":1.9558,"BRL":3.4307,"CAD":1.3693,"CHF":1.04,"CNY":6.7105,"CZK":27.57,"DKK":7.4708,"GBP":0.7316,"HKD":8.3958,"HRK":7.6303,"HUF":299.58,"IDR":14081.0,"ILS":4.2762,"INR":67.343,"JPY":129.59,"KRW":1183.3,"MXN":16.367,"MYR":3.964,"NOK":8.6506,"NZD":1.4499,"PHP":48.092,"PLN":4.0647,"RON":4.4168,"RUB":61.828,"SEK":9.3445,"SGD":1.4719,"THB":35.187,"TRY":2.8145,"USD":1.083,"ZAR":12.995}}
```

**Comment by incarnateTheGreat** [comment]
I'm having a similar problem. I'm trying to use the Fixer.io example to compare a currency to EUR, but I get an fx error.
