### ISSUE TITLE
502 error message

### ISSUE THREAD

**Issue by makarid** [fixerAPI/fixer#98]
Hello, i use this API at least 2 weeks and i hadn't any problem until today.I get Connection timeout error and now i get 502 error.I make a call every 10-15 seconds which means i am not spamming to get rate limits.Does anyone has the same issue?
Thanks for your help and for creating this API!

**Comment by hakanensari** [comment]
It sounds like an [old issue](https://github.com/hakanensari/fixer/issues/55) may have reared its head. I'll look into this.
