### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by MrShayne** [fixerAPI/fixer#99]
I am trying to call this api using JS xhr but I get 403. But if I call the api via browser or postman it works fine. 
![image](https://user-images.githubusercontent.com/11885512/35086044-09d32098-fc66-11e7-8a92-ffbec76f9404.png)

![image](https://user-images.githubusercontent.com/11885512/35086028-fe687e38-fc65-11e7-97e0-6c067ca2a663.png)

**Comment by MrShayne** [comment]
would be very great if I can get some help on that @hakanensari

**Comment by hakanensari** [comment]
@MrShayne I believe you need to [use the `Origin` header](https://hacks.mozilla.org/2009/07/cross-site-xmlhttprequest-with-cors/) when doing the cross-site XHR.
